variables:
  DOCKER_HOST: "tcp://localhost:2375"

stages:
  - build
  - predeploy
  - deploy

services:
  - name: docker:dind
    command: ["--tls=false"]
    privileged: true
    volumes:
      - "/certs/client"
      - "/var/run/docker.sock:/var/run/docker.sock"

before_script:
  - export DOCKER_TLS_CERTDIR=""
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build-app:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

deploy:
  stage: deploy
  script:
    - echo "Deploying to Swarm"
    - ssh user@swarm-manager "docker service update --image $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME jekyll_site || docker service create --name jekyll_site -p 4000:4000 $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"
