title: "Brandenburger Digitaltag 2025"
description: "Digitale Vernetzung für Kommunen, Behörden und zivilgesellschaftliche Initiativen in Brandenburg"
author: "Forum Digitales Brandenburg"
baseurl: ""
url: "https://brandenburger-digitaltag.de"
theme: null

permalink: /:title/

logo:
  mobile: "images/logo/Brandenburger-Digitaltag-Logo.png"
  mobile_height: "32px"
  desktop: "images/logo/Brandenburger-Digitaltag-Logo.png"
  desktop_height: "32px"

home:
  limit_services: 6

collections:
  services:
    output: true
    sort_by: weight
  team:
    output: true

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
