version: '3.8'

services:
  jekyll_app:
    image: ${CI_REGISTRY_IMAGE}/${PROJECT}:latest
    restart: unless-stopped
    networks:
      public:
    ports:
      - "4000:4000"
    labels:
      - traefik.enable=true
      - traefik.docker.network=public
      - traefik.http.routers.jekyll.rule=Host(`jekyll.local`)
      - traefik.http.services.jekyll.loadbalancer.server.port=4000

networks:
  public:
    external: true
