version: '3.8'

services:
  jekyll_app:
    build:
      context: .
    labels:
      - traefik.enable=true
      - traefik.docker.network=public
      - traefik.http.routers.jekyll.rule=Host(`jekyll.local`)
